server:
  port: 8090

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:checkoutdb
    username:
    password:
    driver-class-name: org.h2.Driver