server:
  port: 8091

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:checkoutdb
    username:
    password:
    driver-class-name: org.h2.Driver
  flyway:
    url: jdbc:h2:mem:checkoutdb
    user: sa
    password:
    locations: classpath:db/migration/
    baseline-on-migrate: true
    enabled: true
    schemas: public
  jpa:
    hibernate:
      ddl-auto: none